#!/bin/sh

# Welcome to the massimoksi laptop script!
# Be prepared to turn your laptop (or desktop, no haters here)
# into an awesome development machine.

fancy_echo() {
    local fmt="$1"; shift

    # shellcheck disable=SC2059
    printf "\n$fmt\n" "$@"
}

brew_install_or_upgrade() {
    if brew_is_installed "$1"; then
        if brew_is_upgradable "$1"; then
            fancy_echo "Upgrading %s ..." "$1"
            brew upgrade "$@"
        else
            fancy_echo "Already using the latest version of %s. Skipping ..." "$1"
        fi
    else
        fancy_echo "Installing %s ..." "$1"
        brew install "$@"
    fi
}

brew_is_installed() {
    local name="$(brew_expand_alias "$1")"

    brew list -1 | grep -Fqx "$name"
}

brew_is_upgradable() {
    local name="$(brew_expand_alias "$1")"

    ! brew outdated --quiet "$name" >/dev/null
}

brew_tap() {
    brew tap "$1" 2> /dev/null
}

brew_expand_alias() {
    brew info "$1" 2>/dev/null | head -1 | awk '{gsub(/:/, ""); print $1}'
}

gem_install_or_update() {
    if gem list "$1" --installed > /dev/null; then
        fancy_echo "Updating %s ..." "$1"
        gem update --quiet "$@"
    else
        fancy_echo "Installing %s ..." "$1"
        gem install --no-ri --no-rdoc --quiet "$@"
    fi
}

run_shell_script() {
    if [ -f $1 ]; then
        CUR_PATH=$CWD
        CMD_PATH=${1%/*}
        CMD_NAME=${1##*/}

        cd $CMD_PATH
        fancy_echo "Running %s ..." "$1"
        . "$CMD_NAME"

        cd $CUR_PATH
    else
        fancy_echo "%s not found. Skipping ..." "$1"
    fi
}

###############################################################################
# Homebrew

if ! command -v brew >/dev/null; then
    fancy_echo "Installing Homebrew ..."
    curl -fsS 'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby

    export PATH="/usr/local/bin:$PATH"
else
    fancy_echo "Homebrew already installed. Skipping ..."
fi

fancy_echo "Updating Homebrew formulas ..."
brew update

###############################################################################
# Rubygems

gem update --system

###############################################################################
# Configuration files

CONF_PATH=$HOME/.laptop
if [ -d $CONF_PATH ]; then
    for f in $CONF_PATH/*.laptop; do
        fancy_echo " ->  ${f##*/}"
        . "$f"
    done
else
    mkdir $CONF_PATH
    fancy_echo "Please create your laptop files in .laptop/."
fi

###############################################################################
# Clean up

brew cleanup -s
gem cleanup
